#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import os

commonfiles = os.getenv("CommonProgramFiles",'..')
appdata = os.getenv('APPDATA','..')

# The paths should be generated by setup script
sys.argv.extend([
	'-i', commonfiles + '/alfanous/indexes/',
	'-c', appdata + '/alfanous/configs/'])

from Gui import *

main()


