.\" Manpage for alfanous-desktop.
.TH man 1 "04 May 2017" "1.0" "alfanous-desktop man page"
.SH NAME
alfanous-desktop \- graphic interface of Alfanous 
.SH SYNOPSIS
alfanous-desktop
.SH DESCRIPTION
alfanous-desktop starts the Qt GUI of Alfanous project.
.SH OPTIONS
The alfanous-desktop does not take any options.
.SH SEE ALSO
alfanous-console(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Abdellah Chelli <abdellahchelli@gmail.com>
